/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 kal.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/kal.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Segmentation_Segment_1001.geometry} material={nodes.Segmentation_Segment_1001.material} position={[0.115, 1.187, 0]} rotation={[0, 0, 2.201]} scale={0.013} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0.631, 0.966, 0.103]} rotation={[-0.025, -0.038, -0.69]} scale={[0.41, 0.039, 0.039]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[0.557, 0.865, 0.102]} rotation={[-0.025, -0.038, -0.809]} scale={[0.41, 0.039, 0.039]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[0.669, 1.075, 0.103]} rotation={[-0.025, -0.038, -0.594]} scale={[0.41, 0.039, 0.039]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[0.798, 0.554, 0.082]} rotation={[Math.PI / 2, -0.791, -3.116]} scale={0.064} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.003']} position={[0.894, 0.671, 0.129]} rotation={[1.359, -0.706, 3.057]} scale={0.059} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.004']} position={[0.995, 0.81, 0.111]} rotation={[1.389, -0.591, 3.094]} scale={0.059} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0.156, 0.672, 0.297]} rotation={[-0.022, 0, 0]} scale={[0.004, 0.004, 1.081]} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.005']} position={[0.183, 0.651, 0.452]} rotation={[Math.PI / 2, 0.545, -Math.PI / 2]} scale={0.096} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[0.193, 1.304, 0.297]} rotation={[-0.022, 0, 0]} scale={[0.004, 0.004, 1.081]} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.006']} position={[0.22, 1.296, 0.381]} rotation={[Math.PI / 2, 0.964, -Math.PI / 2]} scale={0.088} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.007']} position={[0.593, 1.105, 0.092]} rotation={[Math.PI / 2, -0.656, -Math.PI]} scale={0.084} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.005']} position={[0.459, 1.163, 0.055]} rotation={[Math.PI / 2, -0.643, Math.PI]} scale={-0.108} />
      <mesh geometry={nodes.Text007.geometry} material={materials['Material.004']} position={[0.435, 0.961, 0.086]} rotation={[1.547, -0.735, 3.084]} scale={0.079} />
      <mesh geometry={nodes.Text008.geometry} material={materials['Material.002']} position={[0.159, 0.62, -0.496]} rotation={[1.598, 0.083, -1.573]} scale={0.099} />
      <mesh geometry={nodes.Text009.geometry} material={materials['Material.003']} position={[0.221, 1.267, -0.436]} rotation={[Math.PI / 2, 0.559, -Math.PI / 2]} scale={0.13} />
    </group>
  )
}

useGLTF.preload('/kal.gltf')
