/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ligament.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ligament.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[30.609, 12.231, -9.121]} rotation={[1.89, 0.881, -2.045]} scale={4.926}>
        <pointLight intensity={1000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[36.146, -7.347, 34.05]} rotation={[1.242, 0.33, -0.76]} scale={4.926}>
        <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.103, -81.038, -0.061]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.049}>
        <OrthographicCamera makeDefault={false} far={100} near={0.001} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.105, 13.143, -0.067]} rotation={[Math.PI / 2, 0, 0]} scale={16.476}>
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1body_cuted1body_cu_0eb81aa.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn4']} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1pasted__Group32974.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn5']} position={[0.001, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface101.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn9']} scale={-1} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface103.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn17']} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface107.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn17']} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface76.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn6']} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface79.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn8']} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface79001.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn8']} rotation={[-Math.PI, 0, 0]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface83.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn9']} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface91.geometry} material={materials.blinn1} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface92.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn12']} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface93.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn19']} position={[0, 0, 0.002]} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface96.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn10']} />
        <mesh geometry={nodes.body_cuted1body_cuted1body_cuted1polySurface99.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn6']} position={[0.004, 0, 0]} scale={-1} />
        <mesh geometry={nodes.body_cuted1body_cuted1skel.geometry} material={materials['s_0081:Skeleton:defaultMat37']} />
        <mesh geometry={nodes.group5_polySurface457.geometry} material={materials.blinn35} />
        <mesh geometry={nodes.innermost6Group63696.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn15']} position={[-0.001, -0.722, 1.67]} rotation={[-2.356, 0, -Math.PI]} scale={1.068} />
        <mesh geometry={nodes.Merged_Bones38Group35199.geometry} material={materials.blinn42} />
        <mesh geometry={nodes.muscle_4Group61378.geometry} material={materials.blinn38} />
        <mesh geometry={nodes.pasted__Group32975.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn5']} />
        <mesh geometry={nodes.polySurface461.geometry} material={materials.blinn37} />
        <mesh geometry={nodes.polySurface463.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn17']} position={[0, 0, -0.001]} />
        <mesh geometry={nodes.polySurface86.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn17']} />
        <mesh geometry={nodes.polySurface466.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn17']} />
        <mesh geometry={nodes.polySurface467.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn18']} />
        <mesh geometry={nodes.polySurface468.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn18']} />
        <mesh geometry={nodes.polySurface469.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn18']} />
        <mesh geometry={nodes.polySurface470.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn18']} />
        <mesh geometry={nodes.polySurface471.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn18']} />
        <mesh geometry={nodes.polySurface472.geometry} material={materials['body_cuted1:body_cuted1:body_cuted1:blinn18']} />
        <mesh geometry={nodes.polySurface465.geometry} material={materials.blinn34} />
        <group rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Group23503.geometry} material={materials['COVERING_FACIA1:COVERING_FACIA1:blinn1']} />
          <mesh geometry={nodes.Mesh003.geometry} material={materials.pasted__pasted__blinn55} />
          <mesh geometry={nodes.Mesh003_1.geometry} material={materials.pasted__pasted__blinn56} />
        </group>
        <mesh geometry={nodes.COVERING_FACIA1AAGroup23503.geometry} material={materials['COVERING_FACIA1:COVERING_FACIA1:blinn1']} />
        <mesh geometry={nodes.Mesh001.geometry} material={materials.pasted__pasted__blinn55} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.pasted__pasted__blinn56} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0.095, -2.717, 4.9]} rotation={[1.619, 0.075, 0.995]} scale={[1.704, 0.01, 0.013]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.483, -1.379, 4.428]} rotation={[1.305, 0.578, 0.778]} scale={[1.543, 0.021, 0.021]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0.525, -1.835, 3.511]} rotation={[1.747, 1.319, -0.074]} scale={[-0.479, -0.007, -0.007]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[0.511, -3.248, 3.571]} rotation={[1.625, -0.332, 0.972]} scale={[0.611, 0.003, 0.005]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0.924, -2.589, 4.904]} rotation={[1.642, 0.053, 0.641]} scale={[1.091, 0.006, 0.008]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-1.08, -2.717, 4.9]} rotation={[1.515, 0.069, 2.256]} scale={[1.704, 0.01, 0.013]} />
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[0.798, -3.079, 6.264]} rotation={[1.461, 0, 0]} />
      <mesh geometry={nodes.Text007.geometry} material={nodes.Text007.material} position={[-2.386, -3.113, 6.296]} rotation={[1.563, 0, 0]} />
      <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} position={[1.147, -0.939, 5.408]} rotation={[1.419, 0, 0]} />
      <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[0.383, -1.672, 3.613]} rotation={[1.07, 0, 0]} />
      <mesh geometry={nodes.Text011.geometry} material={nodes.Text011.material} position={[0.69, -3.701, 4.034]} rotation={[1.484, 0, 0]} />
      <mesh geometry={nodes.Text012.geometry} material={nodes.Text012.material} position={[1.506, -2.936, 5.452]} rotation={[1.719, 0, 0]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[0.982, -1.292, 4.862]} rotation={[-0.691, -0.442, -0.985]} scale={0.21} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-1.312, -1.368, 4.84]} rotation={[-0.691, 0.442, 0.985]} scale={[-0.21, 0.21, 0.21]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[2.571, 0.382, -0.422]} rotation={[-3.139, 0.7, -3.12]} scale={[0.238, 0.238, -0.238]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-2.86, 0.428, -0.203]} rotation={[0, 0.765, 0]} scale={0.238} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[1.052, -2.478, 1.48]} rotation={[-0.609, 0.203, -0.564]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-1.095, -2.674, 1.264]} rotation={[-0.609, -0.203, 0.564]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[-0.809, -0.568, -0.308]} rotation={[1.305, 0.578, 0.942]} scale={[1.543, 0.021, 0.021]} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[-0.124, 0.142, 0.785]} rotation={[1.114, 0, 0]} scale={0.481} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[2.998, 2.016, 1.676]} rotation={[0.634, 0, 0]} scale={0.162} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[-3.332, 2.081, 1.588]} rotation={[0.634, 0, 0]} scale={[-0.162, 0.162, 0.162]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[-2.383, 1.043, 5.811]} rotation={[1.305, 0.578, 0.942]} scale={[1.543, 0.021, 0.021]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[-2.801, 1.949, 4.041]} rotation={[1.305, 0.578, 0.942]} scale={[1.543, 0.021, 0.021]} />
      <mesh geometry={nodes.Text003.geometry} material={nodes.Text003.material} position={[-2.677, 0.698, 5.84]} rotation={[0.974, 0, 0]} />
      <mesh geometry={nodes.Text004.geometry} material={nodes.Text004.material} position={[-3.061, 1.587, 4.165]} rotation={[1.049, 0, 0]} />
      <mesh geometry={nodes.Text005.geometry} material={nodes.Text005.material} position={[-1.753, -0.95, 1.395]} rotation={[1.134, 0, 0]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-1.123, -0.473, 1.366]} rotation={[1.305, 0.578, 0.942]} scale={[1.543, 0.021, 0.021]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-1.376, 1.231, 0.306]} rotation={[1.305, 0.578, 0.942]} scale={[1.543, 0.021, 0.021]} />
      <mesh geometry={nodes.Text002.geometry} material={nodes.Text002.material} position={[-1.824, 0.944, 0.364]} rotation={[1.035, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ligament.gltf')
